server:
  port: 0

spring:
  application:
    name: ACCOUNTSERVICE

  datasource:
    url: jdbc:postgresql://localhost:5432/accountServiceDb
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false

eureka:
  instance:
    prefer-ip-address: true

  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
