# =========================
# COMMON CONFIG
# =========================

eureka:
  instance:
    prefer-ip-address: true

  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

---

# =========================
# USER SERVICE
# =========================

spring:
  config:
    activate:
      on-profile: user-service

server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/bankdb
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false

---

# =========================
# ACCOUNT SERVICE
# =========================

spring:
  config:
    activate:
      on-profile: account-service

server:
  port: 8082

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/bankdb
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

---

# =========================
# LOAN SERVICE
# =========================

spring:
  config:
    activate:
      on-profile: loan-service

server:
  port: 8083

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/bankdb
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

---

# =========================
# TRANSACTION SERVICE
# =========================

spring:
  config:
    activate:
      on-profile: transaction-service

server:
  port: 8084

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/bankdb
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
