server:
  port: 0

spring:
  application:
    name: TRANSACTIONSERVICE

  # Config Server (safe mode)
  config:
    import: optional:configserver:http://localhost:8085



  # (Optional – only if this service uses DB)
  datasource:
    url: jdbc:postgresql://localhost:5432/TRANSACTIONdb
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false

eureka:
  instance:
    prefer-ip-address: true

  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
